// <auto-generated />
using System;
using FinalProjectGroup3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectGroup3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectGroup3.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FurColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAutoFeeder")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            FurColor = "Orange",
                            HasAutoFeeder = true,
                            Name = "Whiskers"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            FurColor = "Black",
                            HasAutoFeeder = false,
                            Name = "Luna"
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            FurColor = "Gray",
                            HasAutoFeeder = true,
                            Name = "Milo"
                        });
                });

            modelBuilder.Entity("FinalProjectGroup3.Models.TeamMemberData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearInProgram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeamMemberData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Sample Student One",
                            YearInProgram = 3
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2002, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Computer Science",
                            FullName = "Sample Student Two",
                            YearInProgram = 4
                        });
                });

            modelBuilder.Entity("FinalProjectGroup3.Models.TravelDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestSeasonToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TravelDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestSeasonToVisit = "Spring",
                            Country = "Japan",
                            Description = "Historic temples, gardens, and traditional tea houses.",
                            DestinationName = "Kyoto",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            BestSeasonToVisit = "Summer",
                            Country = "Greece",
                            Description = "Whitewashed cliffside villages overlooking the Aegean Sea.",
                            DestinationName = "Santorini",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            BestSeasonToVisit = "Fall",
                            Country = "Canada",
                            Description = "Turquoise lakes surrounded by the Canadian Rockies.",
                            DestinationName = "Banff",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("FinalProjectGroup3.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("bit");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Engine = "Proprietary",
                            IsMultiplayer = false,
                            ReleaseYear = 2017,
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Engine = "Unreal Engine",
                            IsMultiplayer = true,
                            ReleaseYear = 2017,
                            Title = "Fortnite"
                        },
                        new
                        {
                            Id = 3,
                            Engine = "MonoGame",
                            IsMultiplayer = true,
                            ReleaseYear = 2016,
                            Title = "Stardew Valley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
